version: '3'

services:
  android:
    platform: linux/arm64
    build:
      context: .
      dockerfile: reproducible-builds/Dockerfile
    command: tail -f /dev/null
    volumes:
      - ./:/project