name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    env:
      CI_DEBUG_TRACE: "true"
      ANDROID_HOME: /opt/android-sdk


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git wget unzip

      - name: Download and set up Android command line tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O /tmp/cli-tools.zip
          unzip -q /tmp/cli-tools.zip -d /tmp/cli-tools
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          mv /tmp/cli-tools/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest
          
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK components
        run: |
          sdkmanager --sdk_root=$ANDROID_HOME --update
          yes | sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0" \
            "extras;google;m2repository" \
            "extras;android;m2repository" \
            "extras;google;google_play_services" \
            "ndk;28.0.13004108" \
            "cmake;3.22.1"
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses

      

      - name: Build with Gradle
        run: ./gradlew clean assemblePlayStagingDebug

      - name: Copy libsignal
        run: |
            LIBSIGNAL_PATH=$(find ~/.gradle/caches/modules-2/files-2.1/org.signal/libsignal-android -name 'libsignal*.aar' -exec dirname {} \; )
            cp ./tapmedia/libsignal-android-0.69.1.aar $LIBSIGNAL_PATH
      - name: Build with Gradle
        run: ./gradlew clean assemblePlayStagingDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: play-prod-release-apk
          path: app/build/outputs/apk/playProd/release/Signal-Android-play-prod-universal-release-1.0.0.apk
          retention-days: 7
